[package]
name = "dynamo-es"
version = "0.4.7"
authors = ["Dave Garred <dave.garred@serverlesstechnology.com>"]
edition = "2021"
license = "Apache-2.0"
keywords = ["cqrs", "event-sourcing", "serverless"]
description = "A DynamoDB implementation of an event repository for cqrs-es."
repository = "https://github.com/serverlesstechnology/dynamo-es"
documentation = "https://docs.rs/dynamo-es"
readme = "README.md"

[dependencies]
cqrs-es = "0.4.5"

async-trait = "0.1.58"
aws-sdk-dynamodb = "0.21.0"
futures = "0.3.25"
serde = { version = "1.0.147", features = ["derive"]}
serde_json = "1.0.87"
tokio = { version = "1.21.2", features = ["rt"] }

[dev-dependencies]
aws-config = "0.51.0"
uuid = { version = "1.2.1", features = ["v4"]}

